export const EVENTS_ENUM = {
  RESIZE: "resize",
  TICK: "tick",
  READY: "ready",
  SHAKE: "shake",
  CHANGE_SCENE: "change-scene",
  ADD_SCENE: "add-scene",
  ADD_WORLD: "add-world",
  DESTROY_WORLD: "destroy-world",
  INIT_WORLD: "init-world",
  SET_WORLD: "set-world",
  CLICK: "click",
  LOADING_STATUS: "loading-status",
  FADING_FINISHED: "fading-finished",
  FADE_TO_ROOM: "fade-to-room",
  FADE_TO_CITY: "fade-to-city",
  READY_CLICK: "ready-click",
  APP_START: "app-start",
};